= Publish to GitHub Pages Example

An example project that demonstrates how to publish the HTML generated by the https://github.com/asciidoctor/asciidoctor-gradle-plugin[Gradle AsciiDoctor Plugin] to GitHub pages
using the https://github.com/ajoberstar/gradle-git/wiki/org.ajoberstar.github-pages[Gradle Git Plugin].

== Setup

You'll need to do the following:

1. Create a *personal access token* in Github (found within Settings -> Applications). 
2. Create a *gh-pages* branch within your destination git repository.
3. Modify you *build.gradle* and *gradle.properties* files (see below).

[code,groovy]
.build.gradle
----
githubPages {
	repoUri = 'https://github.com/asciidoctor/asciidoctor-gradle-examples.git' // <1>
	credentials { // <2>
		username = project.hasProperty('githubToken') ? project.githubToken : ''
		password = ''
	}

	pages {
		from 'build/asciidoc/html5'
	}
}
----
<1> The *repoUri* property should be set to the destination repo.
<2> Use the personal access token from step 1 to set the *githubToken* property in a gradle.properties file within
the root of the project or better yet in ~/.gradle/gradle.properties

== Usage

1. Add your asciidoc files to `src/docs/asciidoc`
2. `./gradlew publishGhPages`