= LiveReload HTML Example

An example project that demonstrates how to convert AsciiDoc to HTML5 using the Asciidoctor Gradle plugin with http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#livereload[Live Reload] support.

== Usage

Convert the AsciiDoc to HTML5 by invoking the 'asciidoctor' goal:

 $ ./gradlew asciidoctor

Open the file _build/asciidoc/html/example-manual.html_  in your browser to see the generated HTML file.

== Live Reload Support

The Gradle build also can support http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#livereload[Live Reload]

Start by running the build with the watch task

 $ ./gradlew asciidoctor watch

This ensures if you modify example-manual.adoc then everything is rebuilt.

Open another terminal and run the liveReload task:

 $ ./gradlew liveReload

Now you can use the https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en[Chrome] or http://feedback.livereload.com/knowledgebase/articles/86242-how-do-i-install-and-use-the-browser-extensions-[Firefox] plugins to automatically reload your browser when the build completes.

IMPORTANT: After installing the Chrome LiveReload extension, you need to check the "Allow access to file URLs" checkbox in Tools > Extensions > LiveReload in order for it to work with local files.

Now try editing example-manual.adoc and watching your browser.
After a brief wait you will observe that the browser is automatically updated with your changes.